package io.xeros.content;

import io.xeros.model.Items;
import io.xeros.model.entity.player.Player;
import io.xeros.model.items.ItemAssistant;

public class UimStorageChest {

    public static boolean isStorageItem(Player c, int itemId) {
        return switch (itemId) {
            case Items.GRACEFUL_BOOTS, Items.GRACEFUL_CAPE, Items.GRACEFUL_GLOVES, Items.GRACEFUL_HOOD, Items.GRACEFUL_LEGS, Items.GRACEFUL_TOP,
                 Items.AGILITY_CAPET, Items.CONSTRUCT_CAPET, Items.COOKING_CAPET, Items.ATTACK_CAPET, Items.CRAFTING_CAPET, Items.DEFENCE_CAPET,
                 Items.FARMING_CAPET, Items.FIREMAKING_CAPET, Items.FISHING_CAPET, Items.FLETCHING_CAPET, Items.HERBLORE_CAPET, Items.HITPOINTS_CAPET,
                 Items.HUNTER_CAPET, Items.MAGIC_CAPET, Items.MINING_CAPET, Items.MUSIC_CAPET, Items.PRAYER_CAPET, Items.RANGING_CAPET,
                 Items.RUNECRAFT_CAPET, Items.SLAYER_CAPET, Items.SMITHING_CAPET, Items.STRENGTH_CAPET, Items.WOODCUT_CAPET, Items.THIEVING_CAPET,
                 Items.COMPLETIONIST_CAPE, Items.MAX_CAPE, Items.MAX_HOOD, Items.ACCUMULATOR_MAX_CAPE, Items.ACCUMULATOR_MAX_HOOD,
                 Items.ARDOUGNE_MAX_CAPE, Items.ARDOUGNE_MAX_HOOD, Items.FIRE_MAX_CAPE, Items.FIRE_MAX_HOOD, Items.INFERNAL_MAX_CAPE,
                 Items.INFERNAL_MAX_HOOD, Items.GUTHIX_MAX_CAPE, Items.GUTHIX_MAX_HOOD, Items.SARADOMIN_MAX_CAPE, Items.SARADOMIN_MAX_HOOD,
                 Items.ZAMORAK_MAX_CAPE, Items.ZAMORAK_MAX_HOOD, Items.IMBUED_GUTHIX_MAX_HOOD, Items.IMBUED_GUTHIX_MAX_CAPE,
                 Items.IMBUED_SARADOMIN_MAX_CAPE, Items.IMBUED_SARADOMIN_MAX_HOOD, Items.IMBUED_ZAMORAK_MAX_CAPE, Items.IMBUED_ZAMORAK_MAX_HOOD,
                 Items.ASSEMBLER_MAX_CAPE, Items.ASSEMBLER_MAX_HOOD, Items.SLAYER_HELMET, Items.SLAYER_HELMET_I, Items.BLACK_SLAYER_HELMET_I,
                 Items.BLACK_SLAYER_HELMET, Items.GREEN_SLAYER_HELMET, Items.GREEN_SLAYER_HELMET_I, Items.RED_SLAYER_HELMET_I,
                 Items.RED_SLAYER_HELMET, Items.PURPLE_SLAYER_HELMET, Items.PURPLE_SLAYER_HELMET_I, Items.TURQUOISE_SLAYER_HELMET,
                 Items.TURQUOISE_SLAYER_HELMET_I, Items.HYDRA_SLAYER_HELMET, Items.HYDRA_SLAYER_HELMET_I, Items.TWISTED_SLAYER_HELMET,
                 Items.TWISTED_SLAYER_HELMET_I, Items.MAGIC_SECATEURS, Items.MAGIC_SECATEURS_NZ, Items.CANNON_BASE, Items.CANNON_BARRELS,
                 Items.CANNON_FURNACE, Items.CANNON_STAND, Items.HERB_SACK, Items.BARROWS_GLOVES, Items.RUNE_GLOVES, Items.MITHRIL_GLOVES,
                 Items.VOID_KNIGHT_GLOVES, Items.VOID_KNIGHT_MACE, Items.VOID_KNIGHT_ROBE, Items.VOID_KNIGHT_TOP, Items.VOID_MAGE_HELM,
                 Items.VOID_MELEE_HELM, Items.VOID_RANGER_HELM, Items.ELITE_VOID_ROBE, Items.ELITE_VOID_TOP, Items.ROGUE_BOOTS, Items.ROGUE_GLOVES,
                 Items.ROGUE_MASK, Items.ROGUE_TOP, Items.ROGUE_TROUSERS, Items.PROSELYTE_CUISSE, Items.PROSELYTE_HAUBERK, Items.PROSELYTE_TASSET,
                 Items.PROSELYTE_SALLET, Items.MOURNER_BOOTS, Items.MOURNER_CLOAK, Items.MOURNER_GLOVES, Items.MOURNER_TOP, Items.MOURNER_TROUSERS,
                 Items.GAS_MASK, Items.LUMBERJACK_BOOTS, Items.LUMBERJACK_HAT, Items.LUMBERJACK_LEGS, Items.LUMBERJACK_TOP, Items.PROSPECTOR_BOOTS,
                 Items.PROSPECTOR_HELMET, Items.PROSPECTOR_JACKET, Items.PROSPECTOR_LEGS, Items.ANGLER_BOOTS, Items.ANGLER_HAT, Items.ANGLER_TOP,
                 Items.ANGLER_WADERS, Items.SHAYZIEN_GLOVES_5, Items.SHAYZIEN_BOOTS_5, Items.SHAYZIEN_GREAVES_5, Items.SHAYZIEN_HELM_5,
                 Items.SHAYZIEN_PLATEBODY_5, Items.FARMERS_BOOTS, Items.FARMERS_BORO_TROUSERS, Items.FARMERS_FORK, Items.FARMERS_JACKET,
                 Items.FARMERS_SHIRT, Items.FARMERS_STRAWHAT, Items.FARMERS_STRAWHAT_2, Items.FARMERS_BORO_TROUSERS_2, Items.OBSIDIAN_PLATEBODY,
                 Items.OBSIDIAN_PLATELEGS, Items.OBSIDIAN_HELMET, Items.FIGHTER_TORSO, Items.JUSTICIAR_CHESTGUARD, Items.JUSTICIAR_FACEGUARD,
                 Items.JUSTICIAR_LEGGUARDS, Items.INQUISITORS_GREAT_HELM, Items.INQUISITORS_PLATESKIRT, Items.INQUISITORS_HAUBERK,
                 Items.PYROMANCER_BOOTS, Items.PYROMANCER_GARB, Items.PYROMANCER_HOOD, Items.PYROMANCER_ROBE, Items.MYSTIC_BOOTS,
                 Items.MYSTIC_BOOTS_DARK, Items.MYSTIC_BOOTS_DUSK, Items.MYSTIC_BOOTS_LIGHT, Items.MYSTIC_GLOVES, Items.MYSTIC_GLOVES_DARK,
                 Items.MYSTIC_GLOVES_DUSK, Items.MYSTIC_GLOVES_LIGHT, Items.MYSTIC_HAT, Items.MYSTIC_HAT_DARK, Items.MYSTIC_HAT_DUSK,
                 Items.MYSTIC_HAT_LIGHT, Items.MYSTIC_ROBE_BOTTOM, Items.MYSTIC_ROBE_BOTTOM_DARK, Items.MYSTIC_ROBE_BOTTOM_DUSK,
                 Items.MYSTIC_ROBE_BOTTOM_LIGHT, Items.INFINITY_BOOTS, Items.INFINITY_BOTTOMS, Items.INFINITY_GLOVES, Items.INFINITY_HAT,
                 Items.INFINITY_TOP, Items.DARK_INFINITY_BOTTOMS, Items.DARK_INFINITY_HAT, Items.DARK_INFINITY_TOP, Items.ANCESTRAL_HAT,
                 Items.ANCESTRAL_ROBE_TOP, Items.ANCESTRAL_ROBE_BOTTOM, 30010, 30012, 30011, 30013, 30014, 30015, 30016, 30017, 30018, 30019, 30020,
                 30021, 30022, 23939, 30110, 30112, 30111, 30113, 30114, 30115, 30116, 30117, 30118, 30119, 30120, 30121, 30122, 30123, 13320, 13321,
                 21187, 21188, 21189, 21192, 21193, 21194, 21196, 21197, 13322, 13323, 13324, 13325, 13326, 20659, 20661, 20663, 20665, 20667, 20669,
                 20671, 20673, 20675, 20677, 20679, 20681, 20683, 20685, 20687, 20689, 20691, 20693, 19557, 12650, 12649, 12651, 12652, 12644, 12645,
                 12643, 11995, 12653, 12655, 13178, 12646, 13179, 13180, 13177, 12648, 13225, 13247, 21273, 12921, 12939, 12940, 21992, 13181, 12816,
                 12654, 22318, 12647, 13262, 19730, 22376, 22378, 22380, 22382, 22384, 20851, 22473, 21291, 22319, 22746, 22748, 22750, 22752, 23760,
                 23757, 23759, 24491 -> true;
            default -> {
                c.sendMessage("@red@Your game mode cannot store: @blu@" + ItemAssistant.getItemName(itemId));
                yield false;
            }
        };
    }
}
